CREATE TABLE IF NOT EXISTS server_schema_version (
    version BIGINT PRIMARY KEY
);
INSERT INTO server_schema_version(version) VALUES (1) ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS contributions (
    radio TEXT NOT NULL, mcc BIGINT NOT NULL, mnc BIGINT NOT NULL,
    area BIGINT NOT NULL, cid BIGINT NOT NULL, device TEXT NOT NULL,
    lat DOUBLE PRECISION NOT NULL, lon DOUBLE PRECISION NOT NULL,
    range_m DOUBLE PRECISION NOT NULL, samples BIGINT NOT NULL, updated_s BIGINT NOT NULL,
    PRIMARY KEY (radio,mcc,mnc,area,cid,device)
);
CREATE INDEX IF NOT EXISTS contributions_device ON contributions(device);
CREATE INDEX IF NOT EXISTS contributions_expiry ON contributions(updated_s);

CREATE TABLE IF NOT EXISTS consensus (
    radio TEXT NOT NULL, mcc BIGINT NOT NULL, mnc BIGINT NOT NULL,
    area BIGINT NOT NULL, cid BIGINT NOT NULL, lat DOUBLE PRECISION NOT NULL,
    lon DOUBLE PRECISION NOT NULL, range_m DOUBLE PRECISION NOT NULL,
    samples BIGINT NOT NULL, devices BIGINT NOT NULL, seeded BIGINT NOT NULL,
    updated_s BIGINT NOT NULL, PRIMARY KEY (radio,mcc,mnc,area,cid)
);
CREATE INDEX IF NOT EXISTS consensus_sync ON consensus(mcc,updated_s);

CREATE TABLE IF NOT EXISTS tower_moderation (
    radio TEXT NOT NULL, mcc BIGINT NOT NULL, mnc BIGINT NOT NULL,
    area BIGINT NOT NULL, cid BIGINT NOT NULL, quarantined BIGINT NOT NULL DEFAULT 1,
    PRIMARY KEY (radio,mcc,mnc,area,cid)
);
CREATE TABLE IF NOT EXISTS tower_removals (
    radio TEXT NOT NULL, mcc BIGINT NOT NULL, mnc BIGINT NOT NULL,
    area BIGINT NOT NULL, cid BIGINT NOT NULL, updated_s BIGINT NOT NULL,
    PRIMARY KEY (radio,mcc,mnc,area,cid)
);
CREATE INDEX IF NOT EXISTS tower_removals_sync ON tower_removals(mcc,updated_s);

CREATE TABLE IF NOT EXISTS server_settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS admin_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id BIGINT NOT NULL, action TEXT NOT NULL, target TEXT NOT NULL, at_s BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS admin_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind TEXT NOT NULL, status TEXT NOT NULL, processed BIGINT NOT NULL DEFAULT 0,
    started_s BIGINT NOT NULL, finished_s BIGINT
);
CREATE TABLE IF NOT EXISTS admin_import_rejections (
    job_id BIGINT NOT NULL REFERENCES admin_jobs(id) ON DELETE CASCADE,
    row_number BIGINT NOT NULL, reason TEXT NOT NULL, input TEXT NOT NULL,
    PRIMARY KEY (job_id,row_number)
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL,
    admin BIGINT NOT NULL DEFAULT 0, suspended BIGINT NOT NULL DEFAULT 0,
    sharing_enabled BIGINT NOT NULL DEFAULT 1, email_verified BIGINT NOT NULL DEFAULT 1
);
CREATE TABLE IF NOT EXISTS account_deleted_keys (
    account_id BIGINT NOT NULL, radio TEXT NOT NULL, mcc BIGINT NOT NULL,
    mnc BIGINT NOT NULL, area BIGINT NOT NULL, cid BIGINT NOT NULL, device TEXT NOT NULL,
    PRIMARY KEY (account_id,radio,mcc,mnc,area,cid,device)
);
CREATE TABLE IF NOT EXISTS email_verifications (
    token_hash TEXT PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    email TEXT NOT NULL, expires_s BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS auth_tokens (
    token_hash TEXT PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    session_id TEXT NOT NULL, kind TEXT NOT NULL, expires_s BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS auth_tokens_user ON auth_tokens(user_id);
CREATE INDEX IF NOT EXISTS auth_tokens_session ON auth_tokens(session_id);
CREATE INDEX IF NOT EXISTS auth_tokens_expiry ON auth_tokens(expires_s);
CREATE TABLE IF NOT EXISTS web_impersonations (
    token_hash TEXT PRIMARY KEY REFERENCES auth_tokens(token_hash) ON DELETE CASCADE,
    admin_token_hash TEXT NOT NULL REFERENCES auth_tokens(token_hash) ON DELETE CASCADE,
    actor_id BIGINT NOT NULL REFERENCES users(id),
    target_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS web_impersonations_admin ON web_impersonations(admin_token_hash);
CREATE TABLE IF NOT EXISTS password_resets (
    token_hash TEXT PRIMARY KEY, user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_s BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS password_resets_expiry ON password_resets(expires_s);

CREATE TABLE IF NOT EXISTS privacy_consents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    purpose TEXT NOT NULL, notice_version TEXT NOT NULL, granted BIGINT NOT NULL, at_s BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS privacy_consents_current ON privacy_consents(account_id,purpose,id);

CREATE TABLE IF NOT EXISTS debug_sessions (
    id TEXT PRIMARY KEY, account_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    client_id TEXT NOT NULL, context_json TEXT NOT NULL,
    created_s BIGINT NOT NULL, updated_s BIGINT NOT NULL,
    finished_s BIGINT, incomplete BIGINT NOT NULL DEFAULT 0, bytes BIGINT NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS debug_sessions_client ON debug_sessions(account_id,client_id);
CREATE INDEX IF NOT EXISTS debug_sessions_account ON debug_sessions(account_id,created_s);
CREATE INDEX IF NOT EXISTS debug_sessions_expiry ON debug_sessions(created_s);
CREATE TABLE IF NOT EXISTS debug_batches (
    session_id TEXT NOT NULL REFERENCES debug_sessions(id) ON DELETE CASCADE,
    seq BIGINT NOT NULL, digest TEXT NOT NULL, bytes BIGINT NOT NULL,
    PRIMARY KEY (session_id,seq)
);
CREATE TABLE IF NOT EXISTS debug_entries (
    session_id TEXT NOT NULL REFERENCES debug_sessions(id) ON DELETE CASCADE,
    seq BIGINT NOT NULL, item BIGINT NOT NULL, kind TEXT NOT NULL,
    elapsed_ms BIGINT NOT NULL, line TEXT NOT NULL,
    PRIMARY KEY (session_id,seq,item)
);
CREATE INDEX IF NOT EXISTS debug_entries_kind ON debug_entries(session_id,kind,seq,item);
